<?php

namespace Database\Seeders;

use App\Models\WorldElementType;
use Illuminate\Database\Seeder;

class ElementTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $elements = [
            // VEGETATION - Trees
            [
                'name' => 'Oak Tree',
                'slug' => 'oak-tree',
                'category' => 'vegetation',
                'description' => 'A majestic oak tree with sprawling branches and deep roots.',
                'density_weight' => 2.50,
                'rarity' => 'common',
                'resource_bonus' => ['resources' => ['wood' => 5], 'bonus_type' => 'one_time'],
                'metadata' => ['biome_restrictions' => ['forest', 'meadow']],
            ],
            [
                'name' => 'Pine Tree',
                'slug' => 'pine-tree',
                'category' => 'vegetation',
                'description' => 'A tall evergreen pine tree with needle-like leaves.',
                'density_weight' => 3.00,
                'rarity' => 'common',
                'resource_bonus' => ['resources' => ['wood' => 4], 'bonus_type' => 'one_time'],
                'metadata' => ['biome_restrictions' => ['forest', 'tundra']],
            ],
            [
                'name' => 'Willow Tree',
                'slug' => 'willow-tree',
                'category' => 'vegetation',
                'description' => 'A graceful willow tree with drooping branches.',
                'density_weight' => 1.50,
                'rarity' => 'uncommon',
                'resource_bonus' => ['resources' => ['wood' => 3, 'magic_essence' => 1], 'bonus_type' => 'one_time'],
                'metadata' => ['biome_restrictions' => ['meadow', 'swamp']],
            ],
            [
                'name' => 'Cherry Blossom',
                'slug' => 'cherry-blossom',
                'category' => 'vegetation',
                'description' => 'A beautiful tree adorned with delicate pink blossoms.',
                'density_weight' => 0.80,
                'rarity' => 'rare',
                'resource_bonus' => ['resources' => ['crystal_shards' => 5, 'magic_essence' => 2], 'bonus_type' => 'one_time'],
                'metadata' => ['biome_restrictions' => ['meadow']],
            ],
            [
                'name' => 'Ancient Tree',
                'slug' => 'ancient-tree',
                'category' => 'vegetation',
                'description' => 'A massive ancient tree that has stood for centuries.',
                'density_weight' => 0.10,
                'rarity' => 'legendary',
                'resource_bonus' => ['resources' => ['wood' => 20, 'magic_essence' => 10], 'bonus_type' => 'repeating', 'cooldown_hours' => 72],
                'metadata' => ['biome_restrictions' => ['forest']],
            ],

            // VEGETATION - Bushes & Flowers
            [
                'name' => 'Rose Bush',
                'slug' => 'rose-bush',
                'category' => 'vegetation',
                'description' => 'A thorny bush with beautiful red roses.',
                'density_weight' => 4.00,
                'rarity' => 'common',
                'resource_bonus' => ['resources' => ['crystal_shards' => 2], 'bonus_type' => 'one_time'],
            ],
            [
                'name' => 'Berry Bush',
                'slug' => 'berry-bush',
                'category' => 'vegetation',
                'description' => 'A bush laden with sweet berries.',
                'density_weight' => 3.50,
                'rarity' => 'common',
                'resource_bonus' => ['resources' => ['wood' => 1, 'crystal_shards' => 1], 'bonus_type' => 'repeating', 'cooldown_hours' => 24],
            ],
            [
                'name' => 'Hedge',
                'slug' => 'hedge',
                'category' => 'vegetation',
                'description' => 'A neatly trimmed decorative hedge.',
                'density_weight' => 2.00,
                'rarity' => 'common',
            ],
            [
                'name' => 'Sunflower',
                'slug' => 'sunflower',
                'category' => 'vegetation',
                'description' => 'A tall flower that follows the sun across the sky.',
                'density_weight' => 3.00,
                'rarity' => 'common',
                'resource_bonus' => ['resources' => ['crystal_shards' => 1], 'bonus_type' => 'one_time'],
                'metadata' => ['biome_restrictions' => ['meadow']],
            ],
            [
                'name' => 'Tulip Patch',
                'slug' => 'tulip-patch',
                'category' => 'vegetation',
                'description' => 'A colorful patch of vibrant tulips.',
                'density_weight' => 2.50,
                'rarity' => 'uncommon',
                'resource_bonus' => ['resources' => ['crystal_shards' => 3], 'bonus_type' => 'one_time'],
            ],
            [
                'name' => 'Wildflowers',
                'slug' => 'wildflowers',
                'category' => 'vegetation',
                'description' => 'A natural arrangement of various wildflowers.',
                'density_weight' => 5.00,
                'rarity' => 'common',
            ],
            [
                'name' => 'Tall Grass',
                'slug' => 'tall-grass',
                'category' => 'vegetation',
                'description' => 'Tall grass swaying in the breeze.',
                'density_weight' => 8.00,
                'rarity' => 'common',
            ],
            [
                'name' => 'Magical Flower',
                'slug' => 'magical-flower',
                'category' => 'vegetation',
                'description' => 'A rare flower that glows with magical energy.',
                'density_weight' => 0.20,
                'rarity' => 'epic',
                'resource_bonus' => ['resources' => ['magic_essence' => 5, 'crystal_shards' => 3], 'bonus_type' => 'repeating', 'cooldown_hours' => 48],
            ],

            // WATER
            [
                'name' => 'Small Pond',
                'slug' => 'small-pond',
                'category' => 'water',
                'description' => 'A tranquil small pond with clear water.',
                'density_weight' => 1.50,
                'rarity' => 'uncommon',
                'resource_bonus' => ['resources' => ['crystal_shards' => 2], 'bonus_type' => 'one_time'],
            ],
            [
                'name' => 'Large Lake',
                'slug' => 'large-lake',
                'category' => 'water',
                'description' => 'A vast lake reflecting the sky above.',
                'density_weight' => 0.30,
                'rarity' => 'rare',
                'resource_bonus' => ['resources' => ['crystal_shards' => 10, 'magic_essence' => 3], 'bonus_type' => 'one_time'],
            ],
            [
                'name' => 'Stream',
                'slug' => 'stream',
                'category' => 'water',
                'description' => 'A babbling stream flowing through the landscape.',
                'density_weight' => 2.00,
                'rarity' => 'common',
                'resource_bonus' => ['resources' => ['crystal_shards' => 1], 'bonus_type' => 'repeating', 'cooldown_hours' => 12],
            ],
            [
                'name' => 'Fountain',
                'slug' => 'fountain',
                'category' => 'water',
                'description' => 'An ornate fountain with cascading water.',
                'density_weight' => 0.50,
                'rarity' => 'rare',
                'resource_bonus' => ['resources' => ['crystal_shards' => 5, 'magic_essence' => 2], 'bonus_type' => 'repeating', 'cooldown_hours' => 24],
            ],
            [
                'name' => 'Waterfall',
                'slug' => 'waterfall',
                'category' => 'water',
                'description' => 'A breathtaking waterfall cascading down rocks.',
                'density_weight' => 0.20,
                'rarity' => 'epic',
                'resource_bonus' => ['resources' => ['crystal_shards' => 15, 'magic_essence' => 5], 'bonus_type' => 'one_time'],
            ],

            // TERRAIN
            [
                'name' => 'Boulder',
                'slug' => 'boulder',
                'category' => 'terrain',
                'description' => 'A large weathered boulder.',
                'density_weight' => 3.00,
                'rarity' => 'common',
                'resource_bonus' => ['resources' => ['stone' => 5], 'bonus_type' => 'one_time'],
            ],
            [
                'name' => 'Rock Formation',
                'slug' => 'rock-formation',
                'category' => 'terrain',
                'description' => 'An interesting natural rock formation.',
                'density_weight' => 1.50,
                'rarity' => 'uncommon',
                'resource_bonus' => ['resources' => ['stone' => 10, 'crystal_shards' => 2], 'bonus_type' => 'one_time'],
            ],
            [
                'name' => 'Pebbles',
                'slug' => 'pebbles',
                'category' => 'terrain',
                'description' => 'A scatter of smooth pebbles.',
                'density_weight' => 6.00,
                'rarity' => 'common',
                'resource_bonus' => ['resources' => ['stone' => 1], 'bonus_type' => 'one_time'],
            ],
            [
                'name' => 'Sand Patch',
                'slug' => 'sand-patch',
                'category' => 'terrain',
                'description' => 'A patch of fine sand.',
                'density_weight' => 4.00,
                'rarity' => 'common',
                'metadata' => ['biome_restrictions' => ['desert', 'meadow']],
            ],
            [
                'name' => 'Dirt Path',
                'slug' => 'dirt-path',
                'category' => 'terrain',
                'description' => 'A worn dirt path through the wilderness.',
                'density_weight' => 2.00,
                'rarity' => 'common',
            ],
            [
                'name' => 'Small Hill',
                'slug' => 'small-hill',
                'category' => 'terrain',
                'description' => 'A gentle rolling hill.',
                'density_weight' => 1.00,
                'rarity' => 'uncommon',
            ],
            [
                'name' => 'Crystal Outcrop',
                'slug' => 'crystal-outcrop',
                'category' => 'terrain',
                'description' => 'A magical outcrop of gleaming crystals.',
                'density_weight' => 0.40,
                'rarity' => 'epic',
                'resource_bonus' => ['resources' => ['crystal_shards' => 20, 'magic_essence' => 8], 'bonus_type' => 'repeating', 'cooldown_hours' => 48],
            ],
            [
                'name' => 'Mountain Peak',
                'slug' => 'mountain-peak',
                'category' => 'terrain',
                'description' => 'A towering mountain peak reaching the clouds.',
                'density_weight' => 0.10,
                'rarity' => 'legendary',
                'resource_bonus' => ['resources' => ['stone' => 50, 'crystal_shards' => 30], 'bonus_type' => 'one_time'],
                'metadata' => ['biome_restrictions' => ['tundra']],
            ],

            // STRUCTURES
            [
                'name' => 'Ancient Ruins',
                'slug' => 'ancient-ruins',
                'category' => 'structure',
                'description' => 'Mysterious ruins from a forgotten civilization.',
                'density_weight' => 0.50,
                'rarity' => 'rare',
                'resource_bonus' => ['resources' => ['stone' => 10, 'magic_essence' => 5], 'bonus_type' => 'one_time'],
            ],
            [
                'name' => 'Stone Statue',
                'slug' => 'stone-statue',
                'category' => 'structure',
                'description' => 'An ancient stone statue of unknown origin.',
                'density_weight' => 0.80,
                'rarity' => 'uncommon',
                'resource_bonus' => ['resources' => ['stone' => 3, 'crystal_shards' => 2], 'bonus_type' => 'one_time'],
            ],
            [
                'name' => 'Wooden Bridge',
                'slug' => 'wooden-bridge',
                'category' => 'structure',
                'description' => 'A sturdy wooden bridge crossing water.',
                'density_weight' => 0.60,
                'rarity' => 'uncommon',
                'resource_bonus' => ['resources' => ['wood' => 8], 'bonus_type' => 'one_time'],
            ],
            [
                'name' => 'Stone Well',
                'slug' => 'stone-well',
                'category' => 'structure',
                'description' => 'An old stone well with fresh water.',
                'density_weight' => 0.70,
                'rarity' => 'uncommon',
                'resource_bonus' => ['resources' => ['stone' => 5, 'crystal_shards' => 3], 'bonus_type' => 'repeating', 'cooldown_hours' => 24],
            ],
            [
                'name' => 'Obelisk',
                'slug' => 'obelisk',
                'category' => 'structure',
                'description' => 'A mysterious obelisk covered in ancient runes.',
                'density_weight' => 0.15,
                'rarity' => 'epic',
                'resource_bonus' => ['resources' => ['stone' => 15, 'magic_essence' => 10, 'crystal_shards' => 10], 'bonus_type' => 'repeating', 'cooldown_hours' => 72],
            ],
            [
                'name' => 'Ancient Temple',
                'slug' => 'ancient-temple',
                'category' => 'structure',
                'description' => 'A magnificent temple from ages past.',
                'density_weight' => 0.05,
                'rarity' => 'legendary',
                'resource_bonus' => ['resources' => ['stone' => 30, 'magic_essence' => 20, 'crystal_shards' => 20, 'wood' => 15], 'bonus_type' => 'repeating', 'cooldown_hours' => 168],
            ],

            // DECORATION
            [
                'name' => 'Wooden Bench',
                'slug' => 'wooden-bench',
                'category' => 'decoration',
                'description' => 'A simple wooden bench for resting.',
                'density_weight' => 1.20,
                'rarity' => 'common',
                'resource_bonus' => ['resources' => ['wood' => 2], 'bonus_type' => 'one_time'],
            ],
            [
                'name' => 'Lamp Post',
                'slug' => 'lamp-post',
                'category' => 'decoration',
                'description' => 'An ornate lamp post that lights the way.',
                'density_weight' => 0.90,
                'rarity' => 'uncommon',
                'resource_bonus' => ['resources' => ['stone' => 3, 'crystal_shards' => 1], 'bonus_type' => 'one_time'],
            ],
            [
                'name' => 'Signpost',
                'slug' => 'signpost',
                'category' => 'decoration',
                'description' => 'A wooden signpost pointing to distant lands.',
                'density_weight' => 1.00,
                'rarity' => 'common',
            ],
            [
                'name' => 'Windmill',
                'slug' => 'windmill',
                'category' => 'decoration',
                'description' => 'A charming windmill with spinning blades.',
                'density_weight' => 0.30,
                'rarity' => 'rare',
                'resource_bonus' => ['resources' => ['wood' => 15, 'stone' => 10], 'bonus_type' => 'one_time'],
            ],
            [
                'name' => 'Garden Gnome',
                'slug' => 'garden-gnome',
                'category' => 'decoration',
                'description' => 'A whimsical garden gnome statue.',
                'density_weight' => 0.80,
                'rarity' => 'uncommon',
                'resource_bonus' => ['resources' => ['magic_essence' => 1], 'bonus_type' => 'one_time'],
            ],
            [
                'name' => 'Mushroom Circle',
                'slug' => 'mushroom-circle',
                'category' => 'decoration',
                'description' => 'A mysterious circle of glowing mushrooms.',
                'density_weight' => 0.40,
                'rarity' => 'rare',
                'resource_bonus' => ['resources' => ['magic_essence' => 8, 'crystal_shards' => 5], 'bonus_type' => 'repeating', 'cooldown_hours' => 48],
                'metadata' => ['biome_restrictions' => ['forest', 'swamp']],
            ],
            [
                'name' => 'Campfire',
                'slug' => 'campfire',
                'category' => 'decoration',
                'description' => 'A warm campfire with crackling flames.',
                'density_weight' => 0.60,
                'rarity' => 'uncommon',
                'resource_bonus' => ['resources' => ['wood' => 3], 'bonus_type' => 'repeating', 'cooldown_hours' => 6],
            ],
        ];

        foreach ($elements as $element) {
            WorldElementType::create($element);
        }
    }
}
